### ISSUE TITLE
Let others legally improve and share this

### ISSUE THREAD

**Issue by ghost** [bsdimp/mk211bsd#1]
Thanks to things like The Berne Convention, in today's world things are automatically copyrighted as "All Rights Reserved" by default (meaning no one else is allowed to make changes or share it) whether that's what you want or not. I hope it's not. Please consider adding copyright & licensing information in your repo so others can know where they stand about what rights they do (or don't) have.

**Comment by bsdimp** [comment]
Will add the appropriate BSDish license when I'm back at a real keyboard.  Great idea...

**Comment by bsdimp** [comment]
Added the License...   "All Rights Reserved" though is now legally meaningless. It used to be required for the Buenos Aires Conventions which applied to rights in Central America. When all the countries there ratified the Berne Convention, it no longer has any meaning (despite being in the BSD template... BSD was born in a time when it did still have meaning and was required to have copyrights in Central and South America). Anyway, hope this is sufficient for your needs and I really hope that this means you'd like to contribute.
